sodo: required
services:
  - docker

before_install:
  - docker build -t francisgu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true francisgu/react-test npm test

after_success:
  - docker build -t multi-client ./client
  - docker build -t multi-nginx ./nginx
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker

  - docker tag multi-client $DOCKER_ID/multi-client
  - docker tag multi-nginx $DOCKER_ID/multi-nginx
  - docker tag multi-server $DOCKER_ID/multi-server
  - docker tag multi-worker $DOCKER_ID/multi-worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push $DOCKER_ID/multi-client
  - docker push $DOCKER_ID/multi-nginx
  - docker push $DOCKER_ID/multi-server
  - docker push $DOCKER_ID/multi-worker
  
  